# Generated by Django 5.0.3 on 2024-06-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_alter_ticket_created_by_alter_ticket_machine_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
