# Generated by Django 5.0.3 on 2024-06-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0003_alter_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tenant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
