# Generated by Django 5.0.3 on 2024-05-31 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinedataapp', '0011_ticket_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
